# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

autoload -Uz compinit && compinit
autoload -Uz vcs_info
precmd_vcs_info() {
    vcs_info
}
precmd_functions+=(
    precmd_vcs_info
)
setopt prompt_subst
zstyle ':vcs_info:git:*' formats '%b'

## asdf
. /usr/local/opt/asdf/libexec/asdf.sh
export ASDF_GOLANG_MOD_VERSION_ENABLED=true

# golang
export PATH="$(go env GOPATH)/bin:$PATH"

# openjdk
export PATH="/usr/local/opt/openjdk/bin:$PATH"
export CPPFLAGS="-I/usr/local/opt/openjdk/include"

## Google Cloud SDK
source "$(brew --prefix)/share/google-cloud-sdk/path.zsh.inc"
source "$(brew --prefix)/share/google-cloud-sdk/completion.zsh.inc"
